### ISSUE TITLE
fix 'noisy' video generation

### ISSUE THREAD

**Issue by Aniruddha-Deb** [Aniruddha-Deb/hackerfx-v2#3]
videos generated using either random bits or data are 'noisy', because the bits in the background change from frame to frame. If a video is passed, generate a random sequence of bits first (maybe do this in a class, like the Hex and Binary Data classes), and then use this class to consistently provide the bitstream that is used while encoding the video. You can maybe also include a reset() method to reset the index to 0 at the start of the next frame.

@Salil03 @basil08 can any one of you take this up?

**Comment by Salil03** [comment]
The video looks too 'clean'. Maybe this is only true for a B/W video like bad apple. Other clips should look fine. Maybe adding some random noise to Binary/HexArray might help.
